config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root :to => redirect("mods")
  resource :mods, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :parts, only: [:create, :edit, :show, :destroy] do
    collection do
      post "search"
    end
  end
  get "/users/:username", to: "users#show", as: :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/mod.rb
class Mod < ApplicationRecord
  validates :name, presence: true

  belongs_to :author_user, class_name: "User", optional: true
end

app/models/part.rb
class Part < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    @current = Current.new
    if session[:user_id]
      @current.user = User.find_by(id: session[:user_id])
      session.delete(:user_id) unless @current.user
    end
  end
end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  layout "with_navbar"

  def new
    @structure = if params[:mod].present? then Mod.find_by(name: params[:mod]).structure else "[]" end
  end

  def create
    @mod = Mod.new(name: params[:name], structure: params[:structure], author_user: @current.user.id)
    @mod.save
  end

  def show
    @mods = Mod.all
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def search
    @results = Part.where("name LIKE ?", "%#{Part.sanitize_sql_like(params[:query])}%").limit(50)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update("search_results", partial: "part_search_results")
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "with_navbar"

  before_action :unauthorized, except: :destroy

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id.to_s
      redirect_to "/"
    else
      flash[:alert] = "Authentication failed!"
      redirect_to controller: :sessions, action: :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to "/"
  end

  private

  def unauthorized
    redirect_to root_path if @current.user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "with_navbar"

  before_action :unauthorized, only: [:new, :create]

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User was successfully created!"
      redirect_to controller: :sessions, action: :new
    else
      flash[:alert] = "User with this nickname already exists!"
      redirect_to controller: :users, action: :new
    end
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  private

  def user_params
    uparams = params.require(:user).permit(:username, :password, :password_confirmation)
    uparams[:role] = 1 # default role: normal (1)
    uparams
  end

  def unauthorized
    redirect_to root_path if @current.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="main-header">
  <%= link_to "Explore", { controller: "mods", action: "show"}, class: "hover-darker-1" %>
  <%= link_to "Editor", { controller: "mods", action: "new"}, class: "hover-darker-1" %>
  <% unless @current.user %>
    <%= link_to "Sign In", { controller: "sessions", action: "new"}, class: "hover-darker-1" %>
    <%= link_to "Sign Up", { controller: "users", action: "new"}, class: "hover-darker-1" %>
  <% else %>
    <%= link_to "Profile", user_path(@current.user.username), class: "hover-darker-1" %>
  <% end %>
</nav>

app/views/application/_part_search_results.html.erb
<% @results.each do |r| %>
  <li class="query-result hover-darker-1 <%= if r.verified then "verified" end %>" onmousedown="window.form_handler.fillForm({name: <%= r.name %>, mass: <%= r.mass %>, width: <%= r.width %>});$(`#search-bar`).val('').trigger('input')">
    <span class="name"><%= r.name %></span>
    <span class="mass"><%= r.mass %> g</span>
    <span class="width"><%= r.width %> cm</span>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PenCalc Tool</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= tag :meta, name: :psj, action: action_name, controller: controller_name %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "jquery-3.7.1.min" %>
    <script src="https://colorjs.io/dist/color.global.js"></script>
    <%= javascript_include_tag "fabric" %>
    <%= javascript_include_tag "init" %>
    <%= javascript_include_tag "resource" %>
    <%= javascript_include_tag "popup" %>
    <%= javascript_include_tag "measure_units" %>
    <%= javascript_include_tag "selectable_list" %>
    <%= javascript_include_tag "part" %>
    <%= javascript_include_tag "parts_handler" %>
    <%= javascript_include_tag "canvas_handler" %>
    <%= javascript_include_tag "form_handler" %>
    <%= javascript_include_tag "editor_logic" %>
    <%= javascript_importmap_tags %>
    <!-- yield :head -->
    <%= yield :head %>
  </head>

  <body>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/with_navbar.html.erb
<%= content_for :content do %>
  <div class="nav-layout">
    <%= render partial: "navbar" %>
    
    <div class="page-content">
      <%= content_for?(:page_content) ? yield(:page_content) : yield %>
    </div> 
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/mods/index.html.erb
<h1>Explore models</h1>

<ul id="feed-container">
  <% @mods.each do |mod| %>
  <li class="mod hover-darker-1">
      <p class="name"><%= mod[:name] %></p>
      <p class="author"><%= mod.author_user.username %></p>
      <p class="date"><%= mod[:created_at] %></p>
  </li>
  <% end %>
</ul>

app/views/mods/new.html.erb
<div class="editor-layout">

  <div class="panel parts-list-panel">
    <ul class="parts-list" id="parts-list"></ul>
  </div>

  <div class="panel tools-panel">
    <div class="tool-button duplicate-tool hover-lighter-1">Duplicate</div>
    <div class="tool-button delete-tool hover-lighter-1">Delete</div>
    <div class="tool-button mirror-tool hover-lighter-1">Mirror</div>
    <div class="tool-button cut-tool hover-lighter-1">Cut</div>

    <div class="tool-button file-options hover-darker-1 new-tool">New</div>
    <div class="tool-button file-options hover-darker-1 open-tool">Open</div>
    <div class="tool-button file-options hover-darker-1 save-tool">Save</div>
  </div>

  <div class="panel canvas-panel">
    <canvas id="editor-canvas"></canvas>
    <input class="mod-name-input" type="text" name="mod-name" placeholder="Type mod name here...">
    <div class="controls-panel">
      <a id="controls-zoom-in" class="hover-darker-1">+</a>
      <a id="controls-zoom-out" class="hover-darker-1">–</a>
      <a id="controls-pan-left" class="hover-darker-1"><</a>
      <a id="controls-pan-right" class="hover-darker-1">></a>
    </div>
  </div>

  <div class="panel part-creator-panel">
    <form class="part-form" id="part-form" action="javascript:void(0);">
      <h3>Add new part</h3>

      <label class="option" for="name">Name</label>
      <input id="name" class="option" placeholder="Dr. Grip Grip" type="text" name="name">

      <label class="option" for="mass">Mass</label>
      <input id="mass" class="option show-measure-units" placeholder="4.3 g" data-units="g" type="text" name="mass">

      <label class="option" for="width">Length</label>
      <input id="width" class="option show-measure-units" placeholder="5.15 cm" data-units="cm" type="text" name="width">

      <label class="option" for="color">Color</label>
      <input id="color" class="option" type="color" name="color">

      <input class="add-button hover-lighter-2" type="submit" value="Add">
    </form>

    <div class="split-line"></div>

    <%= form_with url: search_parts_path, method: :post, class: "search-form" do |form| %>
      <span>or search in database</span>
      <div class="search-bar-container">
        <%= form.search_field :query, oninput: "this.form.requestSubmit()", id: "search-bar", class: "search-bar", type: "text", autocomplete: "off" %>
        <ul class="search-results" id="search_results"></ul>
      </div>
    <% end %>
  </div>

  <div class="panel calc-info-panel"></div>
</div>

<%= content_tag :div, id: "data-element", style: "display: none", data: {structure: @structure} do %>
<% end %>

app/views/mods/show.html.erb
<h1>Explore models</h1>

<ul id="feed-container">
  <% @mods.each do |mod| %>
  <li class="mod hover-darker-1">
      <p class="name"><%= mod[:name] %></p>
      <p class="author"><%= mod.author_user.username %></p>
      <p class="date"><%= mod[:created_at] %></p>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2 style="color: red"><%= flash.alert %></h2>
<h2 style="color: red"><%= flash.notice %></h2>
<h1>Sign Up</h1>

<%= form_with model: @user, method: :create, class: "pretty" do |form| %>
  <%= form.label :username, "Username" %>
  <%= form.text_field :username %>
  <%= form.label :password, "Password" %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation, "Repeat password" %>
  <%= form.password_field :password_confirmation %>
  <%= form.submit "Register", disable_with: 'Registering...' %>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>
<h2>Username: <%= @user.username %></h2>
<%= 
  if @current.user && @current.user.id == @user.id then 
    button_to "Sign Out", { controller: :sessions, action: :destroy }, method: :delete 
  end 
%>